name: ci
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/dependabot.yml'
  pull_request:
env:
  CHART_NAME: my-chart
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: sign-in to registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io -u $ --password-stdin
      - name: prepare environment variables
        run: |
          shortSha=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "IMAGE_TAG=$shortSha" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$CHART_NAME" >> $GITHUB_ENV
      - name: package artifact
        run: |
          helm package $CHART_NAME --version $IMAGE_TAG
      - name: push image in registry
        if: ${{ github.event_name == 'push' }}
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://$IMAGE_NAME

