name: ci-oras
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/dependabot.yml'
      - '.github/workflows/ci-helm.yaml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/dependabot.yml'
      - '.github/workflows/ci-helm.yaml'
      - '.github/workflows/ci-policies.yaml'
env:
  CHART_NAME: my-chart
  IMAGE_TAG: 0.1.0
  KPT_VERSION: 1.0.0-beta.24
  NOMOS_VERSION: 1.14.0
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: kustomize build
        id: kustomize
        run: |
          mkdir hydrated-manifests
          kustomize build . --enable-helm -o hydrated-manifests/hydrated-manifests.yaml
      - name: kustomize build errors in summary
        if: ${{ failure() && steps.kustomize.outcome == 'failure' }}
        run: |
          echo "❌ kustomize build errors:" >> $GITHUB_STEP_SUMMARY
          set +e
          echo '```' >> $GITHUB_STEP_SUMMARY
          kustomize build . --enable-helm 2>&1 &>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          set -e
      - name: install kpt
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v${KPT_VERSION}/kpt_linux_amd64 > kpt
          chmod +x kpt
      - name: install nomos	
        if: ${{ always() }}
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v${NOMOS_VERSION}/nomos_linux_amd64 > nomos
          chmod +x nomos
      - name: nomos vet	
        if: ${{ always() }}
        id: vet
        run: |
          ./nomos vet --path hydrated-manifests --no-api-server-check --source-format unstructured --namespace $CHART_NAME
      - name: nomos vet errors in summary
        if: ${{ failure() && steps.vet.outcome == 'failure' }}
        run: |
          echo "❌ nomos vet errors:" >> $GITHUB_STEP_SUMMARY
          set +e
          echo '```' >> $GITHUB_STEP_SUMMARY
          ./nomos vet --path hydrated-manifests --no-api-server-check --source-format unstructured --namespace $CHART_NAME 2>&1 | grep KNV &>> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          set -e
      - name: kubeval
        id: kubeval
        if: ${{ always() }}
        run: |
          ./kpt fn eval hydrated-manifests --results-dir tmp --image gcr.io/kpt-fn/kubeval:v0.3 -- strict=true ignore_missing_schemas=true
      - name: kubeval errors in summary
        if: ${{ failure() && steps.kubeval.outcome == 'failure' }}
        run: |
          if [ -f tmp/results.yaml ]; then
            echo "❌ kubeval errors:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat tmp/results.yaml | yq -r '.items[]?.results' -o json | jq -r '.[]? | "\(.message)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            rm tmp/results.yaml
          fi
      - name: gatekeeper
        id: gatekeeper
        if: ${{ always() }}
        run: |
          kustomize build policies/ > hydrated-manifests/policies.yaml
          ./kpt fn eval hydrated-manifests --results-dir tmp --image gcr.io/kpt-fn/gatekeeper:v0.2
      - name: gatkeeper errors in summary
        if: ${{ failure() && steps.gatekeeper.outcome == 'failure' }}
        run: |
          if [ -f tmp/results.yaml ]; then
            echo "❌ gatekeeper errors:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat tmp/results.yaml | yq -r '.items[]?.results' -o json | jq -r '.[]? | "\(.message)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            rm tmp/results.yaml
          fi
      - name: trivy scan
        id: trivy
        if: ${{ always() }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: ./hydrated-manifests
          exit-code: 1
          format: json
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: trivy-errors.json
      - name: trivy errors in summary
        if: ${{ failure() && steps.trivy.outcome == 'failure' }}
        run: |
          if [ -f trivy-errors.json ]; then
            echo "❌ trivy errors:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat trivy-errors.json | jq -r '.Results[]? | "\(.Misconfigurations[]?.Message)"' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            rm trivy-errors.json
          fi
      - name: create kind cluster
        if: ${{ always() }}
        run: |
          kind version
          kind create cluster
      - name: kubectl apply
        id: deploy
        if: ${{ always() }}
        run: |
          kubectl create ns $CHART_NAME
          kubectl apply -f hydrated-manifests/hydrated-manifests.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/$CHART_NAME -n $CHART_NAME
      - name: kubectl apply errors in summary
        if: ${{ failure() && steps.deploy.outcome == 'failure' }}
        run: |
          echo "❌ kubectl apply errors:" >> $GITHUB_STEP_SUMMARY
          echo '`kubectl get events:`' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          kubectl get events -n $CHART_NAME >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '`kubectl logs:`' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          kubectl logs -l app.kubernetes.io/name=$CHART_NAME -n $CHART_NAME >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
  diff:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install kpt
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v${KPT_VERSION}/kpt_linux_amd64 > kpt
          chmod +x kpt
      - name: kpt get base ref
        run: |
          mkdir base-ref-resources
          ./kpt pkg get https://github.com/${{ github.repository }}.git/@${{ github.base_ref }} base-ref-resources
          rm base-ref-resources/ci-with-helm/Kptfile
      - name: kustomize build current branch
        run: |
          mkdir hydrated-manifests
          kustomize build . --enable-helm -o hydrated-manifests/hydrated-manifests.yaml
      - name: kustomize build base ref
        run: |
          mkdir base-ref-resources/hydrated-manifests
          kustomize build base-ref-resources/ci-with-helm/ --enable-helm -o base-ref-resources/hydrated-manifests/hydrated-manifests.yaml
      - name: diff
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          set +e
          diff base-ref-resources/hydrated-manifests/hydrated-manifests.yaml hydrated-manifests/hydrated-manifests.yaml >> $GITHUB_STEP_SUMMARY
          set -e
          echo '```' >> $GITHUB_STEP_SUMMARY
  artifact:
    needs: tests
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: oras login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io -u $ --password-stdin
      - name: tar
        run: |
          tar -czf $CHART_NAME.tar.gz kustomization.yaml $CHART_NAME/
      - name: oras push
        if: ${{ github.event_name == 'push' }}
        run: |
          oras push ghcr.io/${{ github.repository_owner }}/$CHART_NAME-oras:$IMAGE_TAG $CHART_NAME.tar.gz
