name: ci-oras
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/dependabot.yml'
      - '.github/workflows/ci-helm.yaml'
  pull_request:
env:
  CHART_NAME: my-chart
  IMAGE_TAG: 0.1.0
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: kustomize build
        id: kustomize
        run: |
          kustomize build . > hydrated-manifests.yaml
      - name: kustomize build errors in summary
        if: ${{ failure() && steps.kustomize.outcome == 'failure' }}
        run: |
          echo "🚫 kustomize build errors:" >> $GITHUB_STEP_SUMMARY
          kustomize build . 2>&1 &>> $GITHUB_STEP_SUMMARY
      - uses: google-github-actions/setup-gcloud@v0.5.0
        if: ${{ always() }}
      - name: install kpt and nomos	
        if: ${{ always() }}
        run: |
          gcloud components install kpt nomos --quiet
      - name: nomos vet	
        if: ${{ always() }}
        id: vet
        run: |
          nomos vet --path hydrated-manifests.yaml --no-api-server-check --source-format unstructured --namespace $CHART_NAME
      - name: nomos vet errors in summary
        if: ${{ failure() && steps.vet.outcome == 'failure' }}
        run: |
          echo "🚫 nomos vet errors:" >> $GITHUB_STEP_SUMMARY
          nomos vet --path hydrated-manifests/$CHART_NAME/templates --no-api-server-check --source-format unstructured --namespace $CHART_NAME 2>&1 | grep KNV &>> $GITHUB_STEP_SUMMARY
      - name: kubeval
        id: kubeval
        if: ${{ always() }}
        run: |
          kpt fn eval hydrated-manifests/$CHART_NAME/templates --results-dir tmp --image gcr.io/kpt-fn/kubeval:v0.3 -- strict=true ignore_missing_schemas=true
      - name: kubeval errors in summary
        if: ${{ failure() && steps.kubeval.outcome == 'failure' }}
        run: |
          if [ -f tmp/results.yaml ]; then
            echo "🚫 kubeval errors:" >> $GITHUB_STEP_SUMMARY
            cat tmp/results.yaml | yq -r '.items[]?.results' -o json | jq -r '.[]? | "❌ \(.message)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
            rm tmp/results.yaml
          fi
      - name: gatekeeper
        id: gatekeeper
        if: ${{ always() }}
        run: |
          cp policies/* hydrated-manifests/$CHART_NAME/templates
          kpt fn eval hydrated-manifests/$CHART_NAME/templates --results-dir tmp --image gcr.io/kpt-fn/gatekeeper:v0.2
      - name: gatkeeper errors in summary
        if: ${{ failure() && steps.gatekeeper.outcome == 'failure' }}
        run: |
          if [ -f tmp/results.yaml ]; then
            echo "🚫 gatekeeper errors:" >> $GITHUB_STEP_SUMMARY
            cat tmp/results.yaml | yq -r '.items[]?.results' -o json | jq -r '.[]? | "❌ \(.message)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
            rm tmp/results.yaml
          fi
      - name: trivy scan
        id: trivy
        if: ${{ always() }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          image-ref: $CHART_NAME
          exit-code: 1
          format: json
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: trivy-errors.json
      - name: trivy errors in summary
        if: ${{ failure() && steps.trivy.outcome == 'failure' }}
        run: |
          if [ -f trivy-errors.json ]; then
            echo "🚫 trivy errors:" >> $GITHUB_STEP_SUMMARY
            cat trivy-errors.json | jq -r '.Results[]? | "❌ \(.Misconfigurations[]?.Message)"' >> $GITHUB_STEP_SUMMARY
            rm trivy-errors.json
          fi
      - name: create kind cluster
        if: ${{ always() }}
        run: |
          kind version
          kind create cluster
      - name: helm install
        id: deploy
        if: ${{ always() }}
        run: |
          kubectl create ns $CHART_NAME
          helm upgrade --install $CHART_NAME ./$CHART_NAME -n $CHART_NAME --wait --timeout=60s
          kubectl wait --for=condition=available --timeout=60s deployment/$CHART_NAME -n $CHART_NAME
      - name: helm install errors in summary
        if: ${{ failure() && steps.deploy.outcome == 'failure' }}
        run: |
          echo "🚫 helm install errors:" >> $GITHUB_STEP_SUMMARY
          echo "❌ kubectl get events:" >> $GITHUB_STEP_SUMMARY
          kubectl get events -n $CHART_NAME >> $GITHUB_STEP_SUMMARY
          echo "❌ kubectl logs:" >> $GITHUB_STEP_SUMMARY
          kubectl logs -l app.kubernetes.io/name=$CHART_NAME -n $CHART_NAME >> $GITHUB_STEP_SUMMARY
  artifact:
    needs: tests
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: oras login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io -u $ --password-stdin
      - name: tar
        run: |
          tar -cf $CHART_NAME.tar kustomization.yaml $CHART_NAME/
      - name: oras push
        if: ${{ github.event_name == 'push' }}
        run: |
          oras push ghcr.io/${{ github.repository_owner }}/$CHART_NAME-oras:$IMAGE_TAG $CHART_NAME.tar
