name: diff
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/dependabot.yml'
      - '.github/workflows/ci-helm.yaml'
  pull_request:
env:
  CHART_NAME: my-chart
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: google-github-actions/setup-gcloud@v0.5.0
      - name: install kpt
        run: |
          gcloud components install kpt --quiet
      - name: kpt get base ref
        run: |
          mkdir base-ref-resources
          kpt pkg get https://github.com/${{ github.repository }}.git/@${{ github.base_ref }} base-ref-resources
          rm base-ref-resources/ci-with-helm/Kptfile
      - name: helm template current branch
        run: |
          mkdir hydrated-manifests
          helm template $CHART_NAME --output-dir hydrated-manifests
      - name: helm template base ref
        run: |
          mkdir base-ref-resources/hydrated-manifests
          helm template base-ref-resources/ci-with-helm/$CHART_NAME --output-dir hydrated-manifests
      - name: diff
        run: |
          diff hydrated-manifests/$CHART_NAME/templates base-ref-resources/hydrated-manifests/$CHART_NAME/templates | sed 's/</++/g;s/>/--/g' >> $GITHUB_STEP_SUMMARY
